spring:
  datasource:
    url: &db_url jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: &db_username ${DB_USERNAME}
      password: &db_password ${DB_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: '1'
    url: *db_url
    user: *db_username
    password: *db_password
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      show-sql: true
      hibernate:
        format_sql: true
        generate_statistics: true
logging:
  level:
    root: INFO
    org:
      hibernate:
        type: trace
        stat: DEBUG

